apiVersion: v1
kind: Service
metadata:
  name: materiais-service
spec:
  type: LoadBalancer
  selector:
    app: materiais-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
